//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamerPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Console
    {
        public int Console_ID { get; set; }
        public string ConsoleName { get; set; }
    }
}
