//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamerPlus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GamerPlusEntities : DbContext
    {
        public GamerPlusEntities()
            : base("name=GamerPlusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Console> Consoles { get; set; }
        public virtual DbSet<NameLogo> NameLogoes { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Developer> Developers { get; set; }
        public virtual DbSet<GamePreview> GamePreviews { get; set; }
        public virtual DbSet<Game> Games { get; set; }
    }
}
