//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamerPlus.Models
{
    using System;
    public partial class GamePreview
    {
        public int PreviewID { get; set; }
        public string Preview { get; set; }
        public Nullable<int> PreviewType { get; set; }
        public Nullable<int> GameID_FK { get; set; }
    }
}
